import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "How to Redeem Google Play Promo Codes",
  description:
    "Step-by-step guide to redeeming Google Play promo codes, in-app purchase codes, and subscription codes on Android and the web.",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">{title}</h2>
      {children}
    </section>
  );
}

function Step({ number, children }: { number: number; children: React.ReactNode }) {
  return (
    <div className="flex gap-4 mb-3">
      <div className="flex-shrink-0 w-7 h-7 rounded-full bg-brand-600 text-white text-sm font-bold flex items-center justify-center mt-0.5">
        {number}
      </div>
      <div className="text-gray-700 dark:text-gray-300 text-sm leading-relaxed">{children}</div>
    </div>
  );
}

function InfoCard({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 mb-4">
      <div className="font-semibold text-blue-800 dark:text-blue-300 text-sm mb-1">{label}</div>
      <div className="text-blue-700 dark:text-blue-400 text-sm">{children}</div>
    </div>
  );
}

function WarningCard({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4 mb-4">
      <div className="text-amber-800 dark:text-amber-300 text-sm">{children}</div>
    </div>
  );
}

export default function GoogleHowToPage() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Header */}
      <header className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-lg font-bold text-brand-600">
            SudoGrab
          </Link>
          <Link
            href="/how-to/apple"
            className="text-sm text-brand-600 hover:underline"
          >
            Apple Guide &rarr;
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-10">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
          How to Redeem Google Play Codes
        </h1>
        <p className="text-gray-500 dark:text-gray-400 mb-8">
          A complete guide to redeeming promo codes, in-app purchase codes, subscription trials, and gift codes on Android and the web.
        </p>

        {/* Types of codes */}
        <Section title="Types of Google Play Codes">
          <div className="grid gap-4 sm:grid-cols-2 mb-6">
            <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
              <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1">One-Time Promo Codes</h3>
              <p className="text-xs text-gray-500">
                Unlock a paid app or in-app purchase for free. Single-use, generated by the developer.
              </p>
            </div>
            <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
              <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1">Subscription Trial Codes</h3>
              <p className="text-xs text-gray-500">
                Get a free trial of a subscription (3&ndash;90 days). A payment method is required since the subscription auto-renews.
              </p>
            </div>
            <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
              <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1">Custom Codes (Multi-Use)</h3>
              <p className="text-xs text-gray-500">
                Developer-chosen code redeemable by thousands of users. Subscription trials only, redeemable in-app only.
              </p>
            </div>
            <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
              <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1">Gift Cards</h3>
              <p className="text-xs text-gray-500">
                Add credit to your Google Play balance. Purchased from retail stores &mdash; not developer-generated.
              </p>
            </div>
          </div>
        </Section>

        {/* Android */}
        <Section title="Redeem on Android">
          <Step number={1}>
            Open the <strong>Google Play Store</strong> app.
          </Step>
          <Step number={2}>
            Tap your <strong>profile icon</strong> in the top-right corner.
          </Step>
          <Step number={3}>
            Tap <strong>&ldquo;Payments &amp; subscriptions&rdquo;</strong>.
          </Step>
          <Step number={4}>
            Tap <strong>&ldquo;Redeem gift code&rdquo;</strong>.
          </Step>
          <Step number={5}>
            Enter or paste your code and tap <strong>&ldquo;Redeem&rdquo;</strong>.
          </Step>
          <Step number={6}>
            Review which Google account will receive the product and tap <strong>&ldquo;Confirm&rdquo;</strong>.
          </Step>
          <InfoCard label="Quick path">
            Play Store &rarr; Profile icon &rarr; Payments &amp; subscriptions &rarr; Redeem gift code
          </InfoCard>
        </Section>

        {/* Web */}
        <Section title="Redeem on the Web">
          <Step number={1}>
            Go to <strong>play.google.com/redeem</strong> in your browser.
          </Step>
          <Step number={2}>
            Sign in to your Google account if prompted.
          </Step>
          <Step number={3}>
            Enter your code and click <strong>&ldquo;Redeem&rdquo;</strong>.
          </Step>
          <Step number={4}>
            Review the account and click <strong>&ldquo;Confirm&rdquo;</strong>.
          </Step>
        </Section>

        {/* Via URL */}
        <Section title="Redeem via Link">
          <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
            Developers can share a direct redemption link. Tapping it pre-fills the code in the Play Store &mdash; you just confirm.
          </p>
          <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4 font-mono text-xs text-gray-700 dark:text-gray-300 break-all mb-4">
            https://play.google.com/redeem?code=<span className="text-brand-600">{'{YOUR_CODE}'}</span>
          </div>
          <p className="text-sm text-gray-500">
            On mobile this opens the Play Store app directly. On desktop it opens the web redemption page.
          </p>
        </Section>

        {/* In-app */}
        <Section title="Redeem From Inside an App">
          <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
            Some codes (especially custom multi-use subscription codes) can only be redeemed from within the app:
          </p>
          <Step number={1}>
            Open the app and initiate a purchase or subscription.
          </Step>
          <Step number={2}>
            On the Google Play purchase screen, tap the <strong>down arrow</strong> next to the payment method.
          </Step>
          <Step number={3}>
            Tap <strong>&ldquo;Redeem code&rdquo;</strong>.
          </Step>
          <Step number={4}>
            Enter your code and tap <strong>&ldquo;Redeem&rdquo;</strong>.
          </Step>
        </Section>

        {/* Differences table */}
        <Section title="What Happens After Redemption?">
          <div className="overflow-x-auto">
            <table className="w-full text-sm border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
              <thead className="bg-gray-100 dark:bg-gray-800">
                <tr>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">Code Type</th>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">What Happens</th>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">Payment Needed?</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">App / IAP Promo</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">Product granted at $0</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">No</td>
                </tr>
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">Subscription Trial</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">Free trial period activates, auto-renews at full price</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400"><strong>Yes</strong></td>
                </tr>
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">Gift Card</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">Balance added to your account</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">No</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Section>

        {/* Gotchas */}
        <Section title="Common Issues &amp; Tips">
          <WarningCard>
            <strong>Country mismatch:</strong> Promo codes are region-locked. A code generated for the US Play Store won&apos;t work with a Google account registered in another country.
          </WarningCard>

          <WarningCard>
            <strong>Codes are case-sensitive:</strong> Enter codes exactly as provided. Don&apos;t add spaces or dashes, even if the code is displayed with separators for readability.
          </WarningCard>

          <WarningCard>
            <strong>Subscription codes require a payment method:</strong> Even for a free trial, Google requires a payment method on file because the subscription auto-renews when the trial ends. Cancel before the trial expires to avoid charges.
          </WarningCard>

          <div className="space-y-3 text-sm text-gray-600 dark:text-gray-400">
            <p>
              <strong className="text-gray-900 dark:text-white">&ldquo;Already redeemed&rdquo; error:</strong> One-time codes can only be used once. If someone else already redeemed the code, it&apos;s gone. Contact the developer for a new code.
            </p>
            <p>
              <strong className="text-gray-900 dark:text-white">Balance limit:</strong> Each country has a maximum Google Play balance. If a gift card would exceed the cap, the redemption fails. Spend some balance first, then try again.
            </p>
            <p>
              <strong className="text-gray-900 dark:text-white">Subscription promo replaces standard trial:</strong> If the app already offers a free trial, a subscription promo code replaces it &mdash; they don&apos;t stack.
            </p>
            <p>
              <strong className="text-gray-900 dark:text-white">Custom multi-use codes are in-app only.</strong> These codes cannot be redeemed through the Play Store &mdash; you must redeem them from within the app during a purchase flow.
            </p>
          </div>
        </Section>

        {/* Limits table */}
        <Section title="Developer Limits (For Reference)">
          <div className="overflow-x-auto">
            <table className="w-full text-sm border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
              <thead className="bg-gray-100 dark:bg-gray-800">
                <tr>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">Code Type</th>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">Limit</th>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">Max Duration</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">App / IAP Promo</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">500 per app per quarter</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">Up to 1 year</td>
                </tr>
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">Subscription (one-time use)</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">10,000 per subscription per quarter</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">Up to 1 year</td>
                </tr>
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">Custom (multi-use)</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">2,000&ndash;99,999 redemptions per code</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">Up to 1 year</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Section>

        {/* CTA */}
        <div className="mt-12 bg-brand-50 dark:bg-brand-900/20 border border-brand-200 dark:border-brand-800 rounded-lg p-6 text-center">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-2">
            Distributing Google Play promo codes?
          </h2>
          <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
            SudoGrab lets you upload codes in bulk, share one link, and track redemptions in real time.
          </p>
          <Link
            href="/"
            className="inline-flex items-center gap-2 px-5 py-2.5 bg-brand-600 text-white rounded-lg hover:bg-brand-700 text-sm font-medium"
          >
            Get Started Free
          </Link>
        </div>

        {/* Footer nav */}
        <div className="mt-10 pt-6 border-t border-gray-200 dark:border-gray-700 flex items-center justify-between text-sm">
          <Link href="/how-to/apple" className="text-brand-600 hover:underline">
            &larr; Apple Guide
          </Link>
          <Link href="/" className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">
            Back to SudoGrab
          </Link>
        </div>
      </main>
    </div>
  );
}
