import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "How to Redeem Apple App Store Promo Codes",
  description:
    "Step-by-step guide to redeeming Apple App Store promo codes, IAP codes, and subscription offer codes on iPhone, iPad, and Mac.",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">{title}</h2>
      {children}
    </section>
  );
}

function Step({ number, children }: { number: number; children: React.ReactNode }) {
  return (
    <div className="flex gap-4 mb-3">
      <div className="flex-shrink-0 w-7 h-7 rounded-full bg-brand-600 text-white text-sm font-bold flex items-center justify-center mt-0.5">
        {number}
      </div>
      <div className="text-gray-700 dark:text-gray-300 text-sm leading-relaxed">{children}</div>
    </div>
  );
}

function InfoCard({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 mb-4">
      <div className="font-semibold text-blue-800 dark:text-blue-300 text-sm mb-1">{label}</div>
      <div className="text-blue-700 dark:text-blue-400 text-sm">{children}</div>
    </div>
  );
}

function WarningCard({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4 mb-4">
      <div className="text-amber-800 dark:text-amber-300 text-sm">{children}</div>
    </div>
  );
}

export default function AppleHowToPage() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Header */}
      <header className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-lg font-bold text-brand-600">
            SudoGrab
          </Link>
          <Link
            href="/how-to/google"
            className="text-sm text-brand-600 hover:underline"
          >
            Google Play Guide &rarr;
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-10">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
          How to Redeem Apple App Store Codes
        </h1>
        <p className="text-gray-500 dark:text-gray-400 mb-8">
          A complete guide to redeeming promo codes, in-app purchase codes, and subscription offer codes on iOS, iPadOS, and macOS.
        </p>

        {/* Types of codes */}
        <Section title="Types of Apple Codes">
          <div className="grid gap-4 sm:grid-cols-2 mb-6">
            <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
              <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1">App Promo Codes</h3>
              <p className="text-xs text-gray-500">
                Download a paid app for free. Generated by the developer. One-time use, expires in 28 days.
              </p>
            </div>
            <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
              <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1">In-App Purchase Codes</h3>
              <p className="text-xs text-gray-500">
                Unlock a specific in-app purchase for free. The app must already be installed on your device.
              </p>
            </div>
            <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
              <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1">Subscription Offer Codes</h3>
              <p className="text-xs text-gray-500">
                Get a free or discounted subscription period. A payment method is required since the subscription auto-renews.
              </p>
            </div>
            <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
              <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1">Gift Cards</h3>
              <p className="text-xs text-gray-500">
                Add credit to your Apple ID balance. Purchased from retail stores &mdash; not developer-generated promo codes.
              </p>
            </div>
          </div>
        </Section>

        {/* iPhone / iPad */}
        <Section title="Redeem on iPhone or iPad">
          <Step number={1}>
            Open the <strong>App Store</strong> app.
          </Step>
          <Step number={2}>
            Tap your <strong>profile icon</strong> in the top-right corner.
          </Step>
          <Step number={3}>
            Tap <strong>&ldquo;Redeem Gift Card or Code&rdquo;</strong>.
          </Step>
          <Step number={4}>
            Tap <strong>&ldquo;Enter Code Manually&rdquo;</strong> (you can also use the camera to scan a physical card).
          </Step>
          <Step number={5}>
            Type or paste your code and tap <strong>&ldquo;Redeem&rdquo;</strong>.
          </Step>
          <Step number={6}>
            The app will download automatically (for app promo codes) or the in-app purchase / subscription will activate.
          </Step>
          <InfoCard label="Quick path">
            App Store &rarr; Profile icon &rarr; Redeem Gift Card or Code &rarr; Enter Code Manually
          </InfoCard>
        </Section>

        {/* Mac */}
        <Section title="Redeem on Mac">
          <Step number={1}>
            Open the <strong>App Store</strong> app on your Mac.
          </Step>
          <Step number={2}>
            Click your <strong>name</strong> in the bottom-left sidebar.
          </Step>
          <Step number={3}>
            Click <strong>&ldquo;Redeem Gift Card&rdquo;</strong>.
          </Step>
          <Step number={4}>
            Enter your code and click <strong>&ldquo;Redeem&rdquo;</strong>.
          </Step>
        </Section>

        {/* Via URL */}
        <Section title="Redeem via Link (Subscription Offer Codes)">
          <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
            Developers can share a direct redemption link for subscription offer codes. When you tap the link on your device, it opens the App Store directly to the redemption flow.
          </p>
          <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4 font-mono text-xs text-gray-700 dark:text-gray-300 break-all mb-4">
            https://apps.apple.com/redeem?ctx=offercodes&id=<span className="text-brand-600">{'{APP_ID}'}</span>&code=<span className="text-brand-600">{'{CODE}'}</span>
          </div>
          <p className="text-sm text-gray-500">
            If the developer provides a link like this, just tap it &mdash; no need to manually enter the code in the App Store.
          </p>
        </Section>

        {/* Differences table */}
        <Section title="What Happens After Redemption?">
          <div className="overflow-x-auto">
            <table className="w-full text-sm border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
              <thead className="bg-gray-100 dark:bg-gray-800">
                <tr>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">Code Type</th>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">What Happens</th>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">App Needed?</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">App Promo</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">App downloads automatically</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">No</td>
                </tr>
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">IAP Code</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">In-app purchase unlocks</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400"><strong>Yes</strong> &mdash; install first</td>
                </tr>
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">Subscription Offer</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">Subscription activates at offer terms</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">No</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Section>

        {/* Gotchas */}
        <Section title="Common Issues &amp; Tips">
          <WarningCard>
            <strong>Country mismatch:</strong> Promo codes are territory-locked. If the code was generated for the US App Store but your Apple ID is registered in another country, it won&apos;t work. The error is often vague (&ldquo;This code has already been redeemed&rdquo;). Check with the developer.
          </WarningCard>

          <WarningCard>
            <strong>IAP codes need the app installed:</strong> Unlike app promo codes, in-app purchase codes require the app to already be on your device. Install the app first, then redeem the code.
          </WarningCard>

          <WarningCard>
            <strong>Subscription codes need a payment method:</strong> Even if the offer is &ldquo;3 months free,&rdquo; Apple requires a payment method on file because the subscription auto-renews at full price after the offer period.
          </WarningCard>

          <div className="space-y-3 text-sm text-gray-600 dark:text-gray-400">
            <p>
              <strong className="text-gray-900 dark:text-white">Codes are case-insensitive</strong> but must be entered exactly &mdash; no extra spaces.
            </p>
            <p>
              <strong className="text-gray-900 dark:text-white">Codes expire after 28 days</strong> (promo and IAP codes). Subscription offer codes have a developer-set expiration.
            </p>
            <p>
              <strong className="text-gray-900 dark:text-white">Each code is single-use.</strong> Once redeemed, it cannot be used again or transferred.
            </p>
            <p>
              <strong className="text-gray-900 dark:text-white">Family Sharing does not apply.</strong> The code redeems to one Apple ID only.
            </p>
          </div>
        </Section>

        {/* Limits table */}
        <Section title="Developer Limits (For Reference)">
          <div className="overflow-x-auto">
            <table className="w-full text-sm border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
              <thead className="bg-gray-100 dark:bg-gray-800">
                <tr>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">Code Type</th>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">Limit</th>
                  <th className="text-left px-4 py-2 font-medium text-gray-700 dark:text-gray-300">Expiration</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">App / IAP Promo</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">100 per version per territory</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">28 days</td>
                </tr>
                <tr className="bg-white dark:bg-gray-900">
                  <td className="px-4 py-2 text-gray-900 dark:text-white">Subscription Offer</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">150,000 per app per quarter</td>
                  <td className="px-4 py-2 text-gray-600 dark:text-gray-400">Developer-configured</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Section>

        {/* CTA */}
        <div className="mt-12 bg-brand-50 dark:bg-brand-900/20 border border-brand-200 dark:border-brand-800 rounded-lg p-6 text-center">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-2">
            Distributing Apple promo codes?
          </h2>
          <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
            SudoGrab lets you upload codes in bulk, share one link, and track redemptions in real time.
          </p>
          <Link
            href="/"
            className="inline-flex items-center gap-2 px-5 py-2.5 bg-brand-600 text-white rounded-lg hover:bg-brand-700 text-sm font-medium"
          >
            Get Started Free
          </Link>
        </div>

        {/* Footer nav */}
        <div className="mt-10 pt-6 border-t border-gray-200 dark:border-gray-700 flex items-center justify-between text-sm">
          <Link href="/how-to/google" className="text-brand-600 hover:underline">
            &larr; Google Play Guide
          </Link>
          <Link href="/" className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">
            Back to SudoGrab
          </Link>
        </div>
      </main>
    </div>
  );
}
